config/routes.rb
Rails.application.routes.draw do
  apipie

  resources :qrcodes
  resources :posts do
    post :upload_images, on: :collection
  end
  get 'link_preview/index'

  get 'dashboard/index'

  devise_for :users, controllers: {
        sessions: 'workers/sessions'
      }

  resources :parcels
  resources :videos
  resources :images
  resources :locators
  resources :messages
  resources :jobs do
    collection do
      get :get_processes
      get :regions
      get :cities
    end
  end

  root 'dashboard#index'
  namespace :admin do
    resources :parcels
    get '/', to: "parcels#index"
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :iprocesses
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :country
	belongs_to :region

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :regions
	has_many :cities
end

app/models/image.rb
class Image < ActiveRecord::Base

  include Rails.application.routes.url_helpers
  has_attached_file :image, styles: {
      thumb: ['200x200#', :jpeg],
      original: ['1920x1200>', :jpeg]
    },
    convert_options: { original: '-strip -auto-orient -colorspace sRGB' }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  belongs_to :user
  belongs_to :post
  def to_json
    {
      files: [
          {
            id: self.id,
            name: read_attribute(:image_file_name),
            size: read_attribute(:image_file_size),
            url: image.url(:thumb),
            delete_url: Rails.application.routes.url_helpers.image_path(self),
            delete_type: "DELETE"
          }
        ]
    }
  end

  attr_reader :image_remote_url

  def image_remote_url=(url_value)
    self.image = URI.parse(url_value)
    @image_remote_url = url_value
  end
end

app/models/iprocess.rb
class Iprocess < ActiveRecord::Base
  has_many :skills
  belongs_to :category
end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :jobs_details
  belongs_to :category
  validates :title, :description, presence: true
  belongs_to :country
end

app/models/jobs_detail.rb
class JobsDetail < ActiveRecord::Base
  belongs_to :job
  belongs_to :iprocess
  belongs_to :skill
end

app/models/locator.rb
class Locator < ActiveRecord::Base
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
end

app/models/parcel.rb
class Parcel < ActiveRecord::Base
	enum status: [ :received, :sent ]
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :content, presence: true
  after_save :extract_url
  has_many :images
  def extract_url
    ExtractPostUrlJob.perform_later(self)
  end
end

app/models/qrcode.rb
class Qrcode < ActiveRecord::Base
	has_attached_file :qrcode
	validates_attachment :qrcode, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	before_validation :set_qrcode
	def set_qrcode
		if qr_img_url.present?
			image_data = qr_img_url[qr_img_url.index("base64,") + "base64,".size, qr_img_url.size]
	    StringIO.open(Base64.decode64(image_data)) do |str|
	      decorate_str(str)
	      str.original_filename = "#{Time.now.to_i}.jpg"
	      # str.content_type = "image/png"
	      self.qrcode = str
	      self.qrcode_content_type = "image/png"
	    end
	  end
  end
  def decorate_str(str)
    str.class.class_eval { attr_accessor :original_filename, :content_type }
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
	belongs_to :country
	has_many :cities
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :iprocess
end

app/models/skills_user.rb
class SkillsUser < ActiveRecord::Base
end

app/models/user.rb
require 'typhoeus/adapters/faraday'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  # mappings dynamic: 'false' do
  #  indexes :email, type: 'string'
  # end
  # has_and_belongs_to_many :skills
  # searchable do
  #   text :email, :settings
  # end

end

app/models/video.rb
class Video < ActiveRecord::Base
	has_attached_file :video,
		:s3_protocol => :https,
		:path => "/public/:class/:attachment/:id_partition/:attachment_:id_:hash_:style.:extension",
		hash_secret: "secret",
		styles: {
        # :medium => {
        #   :geometry => "640x480",
        #   :format => 'mp4'
        # },
        :thumb => { :geometry => "160x120", :format => 'jpeg', :time => 15}
    }, :processors => [:transcoder]
	validates_attachment_content_type :video, content_type: /\Avideo\/.*\Z/
end

app/controllers/locators_controller.rb
class LocatorsController < ApplicationController
  before_action :set_locator, only: [:show, :edit, :update, :destroy]

  # GET /locators
  # GET /locators.json
  def index
    @locators = Locator.all
  end

  # GET /locators/1
  # GET /locators/1.json
  def show
  end

  # GET /locators/new
  def new
    @locator = Locator.new
  end

  # GET /locators/1/edit
  def edit
  end

  # POST /locators
  # POST /locators.json
  def create
    @locator = Locator.new(locator_params)

    respond_to do |format|
      if @locator.save
        format.html { redirect_to @locator, notice: 'Locator was successfully created.' }
        format.json { render :show, status: :created, location: @locator }
      else
        format.html { render :new }
        format.json { render json: @locator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locators/1
  # PATCH/PUT /locators/1.json
  def update
    respond_to do |format|
      if @locator.update(locator_params)
        format.html { redirect_to @locator, notice: 'Locator was successfully updated.' }
        format.json { render :show, status: :ok, location: @locator }
      else
        format.html { render :edit }
        format.json { render json: @locator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locators/1
  # DELETE /locators/1.json
  def destroy
    @locator.destroy
    respond_to do |format|
      format.html { redirect_to locators_url, notice: 'Locator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locator
      @locator = Locator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def locator_params
      params.require(:locator).permit(:name, :lat, :lng)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/locators_helper.rb
module LocatorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/locators/_form.html.erb
<style>
  /* Always set the map height explicitly to define the size of the div
   * element that contains the map. */
  #map {
    height: 100%;
  }
  /* Optional: Makes the sample page fill the window. */
  html, body {
    height: 100%;
    margin: 0;
    padding: 0;
  }
  .controls {
    margin-top: 10px;
    border: 1px solid transparent;
    border-radius: 2px 0 0 2px;
    box-sizing: border-box;
    -moz-box-sizing: border-box;
    height: 32px;
    outline: none;
    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
  }

  #pac-input {
    background-color: #fff;
    font-family: Roboto;
    font-size: 15px;
    font-weight: 300;
    margin-left: 12px;
    padding: 0 11px 0 13px;
    text-overflow: ellipsis;
    width: 300px;
  }

  #pac-input:focus {
    border-color: #4d90fe;
  }

  .pac-container {
    font-family: Roboto;
  }

  #type-selector {
    color: #fff;
    background-color: #4d90fe;
    padding: 5px 11px 0px 11px;
  }

  #type-selector label {
    font-family: Roboto;
    font-size: 13px;
    font-weight: 300;
  }
  #target {
    width: 345px;
  }
</style>
<%= simple_form_for(@locator, html: { class: 'form-verical' }) do |f| %>
<% if @locator.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@locator.errors.count, "error") %>
    prohibited this locator from being saved:</h2>

  <ul>
    <% @locator.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= f.input :name %>
<%= f.input :lat %>
<%= f.input :lng %>

<input id="pac-input" class="controls" type="text" placeholder="Search Box">
<div id="map" style="height: 400px;"></div>
<br/>
<div class="form-group">
  <%= f.button :submit %>
</div>
<% end %>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAAmZx6BM8z4uZZvDkLZ6uVjOGjKBVsBZA&libraries=places&callback=initAutocomplete" async defer></script>

app/views/locators/edit.html.erb
<h1>Editing Locator</h1>

<%= render 'form' %>

<%= link_to 'Show', @locator %> |
<%= link_to 'Back', locators_path %>

app/views/locators/index.html.erb
<p id="notice"><%= notice %></p>
<button onclick="PrintHAF.print()">Print</button>
<h1>Listing Locators</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Lat</th>
      <th>Lng</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locators.each do |locator| %>
      <tr>
      <td><%= locator.id %></td>
      <td><%= locator.name %></td>
      <td><%= locator.lat %></td>
      <td><%= locator.lng %></td>
        <td><%= link_to 'Show', locator %></td>
        <td><%= link_to 'Edit', edit_locator_path(locator) %></td>
        <td><%= link_to 'Destroy', locator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Locator', new_locator_path %>
<div id="footer_wrapper">
  <div id="footer_content">
    Total 4923
  </div>
</div>

app/views/locators/new.html.erb
<h1>New Locator</h1>

<%= render 'form' %>

<%= link_to 'Back', locators_path %>

app/views/locators/show.html.erb
<p id="notice"><%= notice %></p>

<dt>Name</dt>
<dd><%= @locator.name %></dd>
<dt>Map :</dt>
<div>
  <img src="https://maps.googleapis.com/maps/api/staticmap?center=<%= @locator.lat %>,<%= @locator.lng %>&zoom=15&size=600x300&maptype=roadmap&markers=color:blue%7Clabel:S%7C<%= @locator.lat %>,<%= @locator.lng %>&key=AIzaSyAjO4PJzWtNNhq8XeijEgWJ02M-Ep0FdJs" alt="" />
</div>
<%= link_to 'Edit', edit_locator_path(@locator) %> |
<%= link_to 'Back', locators_path %>