config/routes.rb
Rails.application.routes.draw do
  apipie

  resources :qrcodes
  resources :posts do
    post :upload_images, on: :collection
  end
  get 'link_preview/index'

  get 'dashboard/index'

  devise_for :users, controllers: {
        sessions: 'workers/sessions'
      }

  resources :parcels
  resources :videos
  resources :images
  resources :locators
  resources :messages
  resources :jobs do
    collection do
      get :get_processes
      get :regions
      get :cities
    end
  end

  root 'dashboard#index'
  namespace :admin do
    resources :parcels
    get '/', to: "parcels#index"
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :iprocesses
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :country
	belongs_to :region

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :regions
	has_many :cities
end

app/models/image.rb
class Image < ActiveRecord::Base

  include Rails.application.routes.url_helpers
  has_attached_file :image, styles: {
      thumb: ['200x200#', :jpeg],
      original: ['1920x1200>', :jpeg]
    },
    convert_options: { original: '-strip -auto-orient -colorspace sRGB' }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  belongs_to :user
  belongs_to :post
  def to_json
    {
      files: [
          {
            id: self.id,
            name: read_attribute(:image_file_name),
            size: read_attribute(:image_file_size),
            url: image.url(:thumb),
            delete_url: Rails.application.routes.url_helpers.image_path(self),
            delete_type: "DELETE"
          }
        ]
    }
  end

  attr_reader :image_remote_url

  def image_remote_url=(url_value)
    self.image = URI.parse(url_value)
    @image_remote_url = url_value
  end
end

app/models/iprocess.rb
class Iprocess < ActiveRecord::Base
  has_many :skills
  belongs_to :category
end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :jobs_details
  belongs_to :category
  validates :title, :description, presence: true
  belongs_to :country
end

app/models/jobs_detail.rb
class JobsDetail < ActiveRecord::Base
  belongs_to :job
  belongs_to :iprocess
  belongs_to :skill
end

app/models/locator.rb
class Locator < ActiveRecord::Base
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
end

app/models/parcel.rb
class Parcel < ActiveRecord::Base
	enum status: [ :received, :sent ]
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :content, presence: true
  after_save :extract_url
  has_many :images
  def extract_url
    ExtractPostUrlJob.perform_later(self)
  end
end

app/models/qrcode.rb
class Qrcode < ActiveRecord::Base
	has_attached_file :qrcode
	validates_attachment :qrcode, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	before_validation :set_qrcode
	def set_qrcode
		if qr_img_url.present?
			image_data = qr_img_url[qr_img_url.index("base64,") + "base64,".size, qr_img_url.size]
	    StringIO.open(Base64.decode64(image_data)) do |str|
	      decorate_str(str)
	      str.original_filename = "#{Time.now.to_i}.jpg"
	      # str.content_type = "image/png"
	      self.qrcode = str
	      self.qrcode_content_type = "image/png"
	    end
	  end
  end
  def decorate_str(str)
    str.class.class_eval { attr_accessor :original_filename, :content_type }
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
	belongs_to :country
	has_many :cities
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :iprocess
end

app/models/skills_user.rb
class SkillsUser < ActiveRecord::Base
end

app/models/user.rb
require 'typhoeus/adapters/faraday'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  # mappings dynamic: 'false' do
  #  indexes :email, type: 'string'
  # end
  # has_and_belongs_to_many :skills
  # searchable do
  #   text :email, :settings
  # end

end

app/models/video.rb
class Video < ActiveRecord::Base
	has_attached_file :video,
		:s3_protocol => :https,
		:path => "/public/:class/:attachment/:id_partition/:attachment_:id_:hash_:style.:extension",
		hash_secret: "secret",
		styles: {
        # :medium => {
        #   :geometry => "640x480",
        #   :format => 'mp4'
        # },
        :thumb => { :geometry => "160x120", :format => 'jpeg', :time => 15}
    }, :processors => [:transcoder]
	validates_attachment_content_type :video, content_type: /\Avideo\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @post = Post.new
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def upload_images
    image_stream = params[:post][:images][0]
    image = Image.new({image: image_stream})
    image.save
    render json: image.to_json, status: :ok
    # images_params.each do |image_param|
    #   p image_param
    #   image = Image.new(image_param)
    #   if @image.save
    #     render json: @image.to_json, status: :ok
    #   else
    #     render json: @image.errors, status: :unprocessable_entity
    #   end
    # end
  end
  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def images_params
      params.require(:post).permit(images: [])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params[:post][:url_extract] ={}
      params.require(:post).permit(:content, :url_extract, :likes_count, :comments_count, image_ids: [])
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.input :likes_count %>
    <%= f.input :comments_count %>
    <input type="text" name="post[image_ids][]" value="108">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>
<div class="container no-padding">
	<%= render partial: "shared/postmodule_container", locals: {post: @post} %>	
</div>
<% @posts.each do |post| %>
  <%= render partial: "shared/post_card", locals: {post: post} %>
<% end %>
<br>

<%= link_to 'New Post', new_post_path %>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".btn-delete.delete").click(function(event) {
			/* Act on the event */
			$(".imageuploadify-details.preview").remove();
			console.log('test');
		});
	});
</script>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<%= form_tag('/posts', method: :get, enforce_utf8: false) do%>
 <%= text_field_tag :content  %>
 <%=submit_tag "Search", :name => nil %>
<% end %>
<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Url extract:</strong>
  <%= @post.url_extract %>
</p>

<p>
  <strong>Likes count:</strong>
  <%= @post.likes_count %>
</p>

<p>
  <strong>Comments count:</strong>
  <%= @post.comments_count %>
</p>

<div class="row">
	<ul class="img-thumbnails">
	  
	<% @post.images.each_with_index do |image, index| %>
		<% if index != 3 %>
			<li class="<%= img_class = index > 3 ? 'hidden' : '' %>">
				<a class="fancybox" rel="<%= @post.id %>" href="<%= image.image.url %>" title="<%= @post.content[0..200] %>">
					<div class="img">
						<%= image_tag image.image.url(:thumb), class: "img-responsive" %>
					</div>
				</a>
			</li>
		<% else %>
		<li>
			<a class="fancybox img-with-plus" rel="<%= @post.id %>" href="<%= image.image.url %>" title="<%= @post.content[0..200] %>">
				<div class="img">
					<div class="overlay">
						<span>3+</span>
					</div>
					<%= image_tag image.image.url(:thumb), class: "img-responsive" %>
				</div>
			</a>
		</li>
		<% end %>
	<% end %>
	</ul>
</div>
<div style="width: 200px; height: 200px; background-color: #cccccc; text-align: center;vertical-align: middle; display: inline-block;">
<span style="vertical-align: middle; line-height: 200px; font-size: 50px;">2+</span>
</div>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<script type="text/javascript">
	
</script>