config/routes.rb
Rails.application.routes.draw do
  apipie

  resources :qrcodes
  resources :posts do
    post :upload_images, on: :collection
  end
  get 'link_preview/index'

  get 'dashboard/index'

  devise_for :users, controllers: {
        sessions: 'workers/sessions'
      }

  resources :parcels
  resources :videos
  resources :images
  resources :locators
  resources :messages
  resources :jobs do
    collection do
      get :get_processes
      get :regions
      get :cities
    end
  end

  root 'dashboard#index'
  namespace :admin do
    resources :parcels
    get '/', to: "parcels#index"
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :iprocesses
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :country
	belongs_to :region

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :regions
	has_many :cities
end

app/models/image.rb
class Image < ActiveRecord::Base

  include Rails.application.routes.url_helpers
  has_attached_file :image, styles: {
      thumb: ['200x200#', :jpeg],
      original: ['1920x1200>', :jpeg]
    },
    convert_options: { original: '-strip -auto-orient -colorspace sRGB' }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  belongs_to :user
  belongs_to :post
  def to_json
    {
      files: [
          {
            id: self.id,
            name: read_attribute(:image_file_name),
            size: read_attribute(:image_file_size),
            url: image.url(:thumb),
            delete_url: Rails.application.routes.url_helpers.image_path(self),
            delete_type: "DELETE"
          }
        ]
    }
  end

  attr_reader :image_remote_url

  def image_remote_url=(url_value)
    self.image = URI.parse(url_value)
    @image_remote_url = url_value
  end
end

app/models/iprocess.rb
class Iprocess < ActiveRecord::Base
  has_many :skills
  belongs_to :category
end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :jobs_details
  belongs_to :category
  validates :title, :description, presence: true
  belongs_to :country
end

app/models/jobs_detail.rb
class JobsDetail < ActiveRecord::Base
  belongs_to :job
  belongs_to :iprocess
  belongs_to :skill
end

app/models/locator.rb
class Locator < ActiveRecord::Base
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
end

app/models/parcel.rb
class Parcel < ActiveRecord::Base
	enum status: [ :received, :sent ]
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :content, presence: true
  after_save :extract_url
  has_many :images
  def extract_url
    ExtractPostUrlJob.perform_later(self)
  end
end

app/models/qrcode.rb
class Qrcode < ActiveRecord::Base
	has_attached_file :qrcode
	validates_attachment :qrcode, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	before_validation :set_qrcode
	def set_qrcode
		if qr_img_url.present?
			image_data = qr_img_url[qr_img_url.index("base64,") + "base64,".size, qr_img_url.size]
	    StringIO.open(Base64.decode64(image_data)) do |str|
	      decorate_str(str)
	      str.original_filename = "#{Time.now.to_i}.jpg"
	      # str.content_type = "image/png"
	      self.qrcode = str
	      self.qrcode_content_type = "image/png"
	    end
	  end
  end
  def decorate_str(str)
    str.class.class_eval { attr_accessor :original_filename, :content_type }
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
	belongs_to :country
	has_many :cities
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :iprocess
end

app/models/skills_user.rb
class SkillsUser < ActiveRecord::Base
end

app/models/user.rb
require 'typhoeus/adapters/faraday'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  # mappings dynamic: 'false' do
  #  indexes :email, type: 'string'
  # end
  # has_and_belongs_to_many :skills
  # searchable do
  #   text :email, :settings
  # end

end

app/models/video.rb
class Video < ActiveRecord::Base
	has_attached_file :video,
		:s3_protocol => :https,
		:path => "/public/:class/:attachment/:id_partition/:attachment_:id_:hash_:style.:extension",
		hash_secret: "secret",
		styles: {
        # :medium => {
        #   :geometry => "640x480",
        #   :format => 'mp4'
        # },
        :thumb => { :geometry => "160x120", :format => 'jpeg', :time => 15}
    }, :processors => [:transcoder]
	validates_attachment_content_type :video, content_type: /\Avideo\/.*\Z/
end

app/controllers/admin/parcels_controller.rb
class Admin::ParcelsController < Admin::BaseController
  before_action :set_admin_parcel, only: [:show, :edit, :update, :destroy]

  # GET /admin/parcels
  # GET /admin/parcels.json
  def index
    @parcels = Parcel.all
  end

  # GET /admin/parcels/1
  # GET /admin/parcels/1.json
  def show
  end

  # GET /admin/parcels/new
  def new
    @parcel = Parcel.new
  end

  # GET /admin/parcels/1/edit
  def edit
  end

  # POST /admin/parcels
  # POST /admin/parcels.json
  def create
    @parcel = Parcel.new(parcel_params)

    respond_to do |format|
      if @parcel.save
        format.html { redirect_to @parcel, notice: 'Parcel was successfully created.' }
        format.json { render :show, status: :created, location: @parcel }
      else
        format.html { render :new }
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/parcels/1
  # PATCH/PUT /admin/parcels/1.json
  def update
    respond_to do |format|
      if @parcel.update(parcel_params)
        format.html { redirect_to @parcel, notice: 'Parcel was successfully updated.' }
        format.json { render :show, status: :ok, location: @parcel }
      else
        format.html { render :edit }
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/parcels/1
  # DELETE /admin/parcels/1.json
  def destroy
    @parcel.destroy
    respond_to do |format|
      format.html { redirect_to admin_parcels_url, notice: 'Parcel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parcel
      @parcel = Parcel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parcel_params
      params.fetch(:parcel, {})
    end
end

app/controllers/parcels_controller.rb
class ParcelsController < ApplicationController
  before_action :set_parcel, only: [:show, :edit, :update, :destroy]

  # GET /parcels
  # GET /parcels.json
  def index
    @parcels = Parcel.all
  end

  # GET /parcels/1
  # GET /parcels/1.json
  def show
  end

  # GET /parcels/new
  def new
    @parcel = Parcel.new
  end

  # GET /parcels/1/edit
  def edit
  end

  # POST /parcels
  # POST /parcels.json
  def create
    @parcel = Parcel.new(parcel_params)

    respond_to do |format|
      if @parcel.save
        format.html { redirect_to @parcel, notice: 'Parcel was successfully created.' }
        format.json { render :show, status: :created, location: @parcel }
      else
        format.html { render :new }
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parcels/1
  # PATCH/PUT /parcels/1.json
  def update
    respond_to do |format|
      if @parcel.update(parcel_params)
        format.html { redirect_to @parcel, notice: 'Parcel was successfully updated.' }
        format.json { render :show, status: :ok, location: @parcel }
      else
        format.html { render :edit }
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parcels/1
  # DELETE /parcels/1.json
  def destroy
    @parcel.destroy
    respond_to do |format|
      format.html { redirect_to parcels_url, notice: 'Parcel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parcel
      @parcel = Parcel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parcel_params
      params.fetch(:parcel, {})
    end
end

app/helpers/admin/parcels_helper.rb
module Admin::ParcelsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/parcels_helper.rb
module ParcelsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/admin/parcels/_form.html.erb
<%= form_for @parcel, :html => { :class => "form-horizontal parcel" } do |f| %>

  <% if @parcel.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@parcel.errors.count, "error") %> prohibited this parcel from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @parcel.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :size, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :size, :class => 'form-control' %>
    </div>
    <%=f.error_span(:size) %>
  </div>
  <div class="form-group">
    <%= f.label :weight, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :weight, :class => 'form-control' %>
    </div>
    <%=f.error_span(:weight) %>
  </div>
  <div class="form-group">
    <%= f.label :total_fee, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :total_fee, :class => 'form-control' %>
    </div>
    <%=f.error_span(:total_fee) %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :status, :class => 'form-control' %>
    </div>
    <%=f.error_span(:status) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                parcels_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/admin/parcels/edit.html.erb
<%- model_class = Parcel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/parcels/index.html.erb
<%- model_class = Parcel -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:size) %></th>
      <th><%= model_class.human_attribute_name(:weight) %></th>
      <th><%= model_class.human_attribute_name(:total_fee) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @parcels.each do |parcel| %>
      <tr>
        <td><%= link_to parcel.id, parcel_path(parcel) %></td>
        <td><%= parcel.name %></td>
        <td><%= parcel.size %></td>
        <td><%= parcel.weight %></td>
        <td><%= parcel.total_fee %></td>
        <td><%= parcel.status %></td>
        <td><%=l parcel.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      parcel_path(parcel), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_parcel_path(parcel), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      parcel_path(parcel),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_parcel_path,
            :class => 'btn btn-primary' %>

app/views/admin/parcels/new.html.erb
<%- model_class = Parcel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/parcels/show.html.erb
<%- model_class = Parcel -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @parcel.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:size) %>:</strong></dt>
  <dd><%= @parcel.size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:weight) %>:</strong></dt>
  <dd><%= @parcel.weight %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total_fee) %>:</strong></dt>
  <dd><%= @parcel.total_fee %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @parcel.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              parcels_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_parcel_path(@parcel), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              parcel_path(@parcel),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>