config/routes.rb
Rails.application.routes.draw do
  apipie

  resources :qrcodes
  resources :posts do
    post :upload_images, on: :collection
  end
  get 'link_preview/index'

  get 'dashboard/index'

  devise_for :users, controllers: {
        sessions: 'workers/sessions'
      }

  resources :parcels
  resources :videos
  resources :images
  resources :locators
  resources :messages
  resources :jobs do
    collection do
      get :get_processes
      get :regions
      get :cities
    end
  end

  root 'dashboard#index'
  namespace :admin do
    resources :parcels
    get '/', to: "parcels#index"
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :iprocesses
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :country
	belongs_to :region

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :regions
	has_many :cities
end

app/models/image.rb
class Image < ActiveRecord::Base

  include Rails.application.routes.url_helpers
  has_attached_file :image, styles: {
      thumb: ['200x200#', :jpeg],
      original: ['1920x1200>', :jpeg]
    },
    convert_options: { original: '-strip -auto-orient -colorspace sRGB' }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  belongs_to :user
  belongs_to :post
  def to_json
    {
      files: [
          {
            id: self.id,
            name: read_attribute(:image_file_name),
            size: read_attribute(:image_file_size),
            url: image.url(:thumb),
            delete_url: Rails.application.routes.url_helpers.image_path(self),
            delete_type: "DELETE"
          }
        ]
    }
  end

  attr_reader :image_remote_url

  def image_remote_url=(url_value)
    self.image = URI.parse(url_value)
    @image_remote_url = url_value
  end
end

app/models/iprocess.rb
class Iprocess < ActiveRecord::Base
  has_many :skills
  belongs_to :category
end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :jobs_details
  belongs_to :category
  validates :title, :description, presence: true
  belongs_to :country
end

app/models/jobs_detail.rb
class JobsDetail < ActiveRecord::Base
  belongs_to :job
  belongs_to :iprocess
  belongs_to :skill
end

app/models/locator.rb
class Locator < ActiveRecord::Base
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
end

app/models/parcel.rb
class Parcel < ActiveRecord::Base
	enum status: [ :received, :sent ]
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :content, presence: true
  after_save :extract_url
  has_many :images
  def extract_url
    ExtractPostUrlJob.perform_later(self)
  end
end

app/models/qrcode.rb
class Qrcode < ActiveRecord::Base
	has_attached_file :qrcode
	validates_attachment :qrcode, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	before_validation :set_qrcode
	def set_qrcode
		if qr_img_url.present?
			image_data = qr_img_url[qr_img_url.index("base64,") + "base64,".size, qr_img_url.size]
	    StringIO.open(Base64.decode64(image_data)) do |str|
	      decorate_str(str)
	      str.original_filename = "#{Time.now.to_i}.jpg"
	      # str.content_type = "image/png"
	      self.qrcode = str
	      self.qrcode_content_type = "image/png"
	    end
	  end
  end
  def decorate_str(str)
    str.class.class_eval { attr_accessor :original_filename, :content_type }
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
	belongs_to :country
	has_many :cities
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :iprocess
end

app/models/skills_user.rb
class SkillsUser < ActiveRecord::Base
end

app/models/user.rb
require 'typhoeus/adapters/faraday'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  # mappings dynamic: 'false' do
  #  indexes :email, type: 'string'
  # end
  # has_and_belongs_to_many :skills
  # searchable do
  #   text :email, :settings
  # end

end

app/models/video.rb
class Video < ActiveRecord::Base
	has_attached_file :video,
		:s3_protocol => :https,
		:path => "/public/:class/:attachment/:id_partition/:attachment_:id_:hash_:style.:extension",
		hash_secret: "secret",
		styles: {
        # :medium => {
        #   :geometry => "640x480",
        #   :format => 'mp4'
        # },
        :thumb => { :geometry => "160x120", :format => 'jpeg', :time => 15}
    }, :processors => [:transcoder]
	validates_attachment_content_type :video, content_type: /\Avideo\/.*\Z/
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user = current_user
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json {
          render json: @image.to_json, status: :ok
        }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :image)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/images/_form.html.erb
<div class="container">
  <h2>Upload file</h2>
  <%= form_for Image.new, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
      <div class="span7">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
          <i class="icon-plus icon-white"></i>
          <span>Add files...</span>
          <%= f.file_field :image %>
        </span>
        <button type="submit" class="btn btn-primary start">
          <i class="icon-upload icon-white"></i>
          <span>Start upload</span>
        </button>
        <button type="reset" class="btn btn-warning cancel">
          <i class="icon-ban-circle icon-white"></i>
          <span>Cancel upload</span>
        </button>
        <button type="button" class="btn btn-danger delete">
          <i class="icon-trash icon-white"></i>
          <span>Delete</span>
        </button>
        <input type="checkbox" class="toggle">
      </div>
      <div class="span5">
        <!-- The global progress bar -->
        <div class="progress progress-success progress-striped active fade">
          <div class="bar" style="width:0%;"></div>
        </div>
      </div>
    </div>
    <!-- The loading indicator is shown during image processing -->
    <div class="fileupload-loading"></div>
    <br>
    <!-- The table listing the files available for upload/download -->
    <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
    </table>
  <% end %>

</div>
<script>
  var fileUploadErrors = {
  maxFileSize: 'File is too big',
  minFileSize: 'File is too small',
  acceptFileTypes: 'Filetype not allowed',
  maxNumberOfFiles: 'Max number of files exceeded',
  uploadedBytes: 'Uploaded bytes exceed file size',
  emptyResult: 'Empty file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-primary">
        <i class="icon-upload icon-white"></i>
        <span>{%=locale.fileupload.start%}</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning">
        <i class="icon-ban-circle icon-white"></i>
        <span>{%=locale.fileupload.cancel%}</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<!-- <script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
        <td class="preview">{% if (file.url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.url%}"></a>
          {% } %}</td>
        <td class="name">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
        </td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2"></td>
        {% } %}
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white"></i>
          <span>{%=locale.fileupload.destroy%}</span>
        </button>
        <input type="checkbox" name="delete" value="1">
      </td>
    </tr>
    {% } %}
</script> -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.url%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.url?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.delete_url) { %}
                <button class="btn btn-danger delete" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<script type="text/javascript" charset="utf-8">
  $(function () {
      // Initialize the jQuery File Upload widget:
      $('#fileupload').fileupload({
        autoUpload: true,
        type: 'POST',
        previewMaxWidth: 100,
        previewMaxHeight: 100,
        url: "/images"
      });
      // 
      // Load existing files:
      $.getJSON($('#fileupload').prop('action'), function (files) {
        var fu = $('#fileupload').data('blueimpFileupload'), 
          template;
        fu._adjustMaxNumberOfFiles(-files.length);
        console.log(files);
        template = fu._renderDownload(files)
          .appendTo($('#fileupload .files'));
        // Force reflow:
        fu._reflow = fu._transition && template.length &&
          template[0].offsetWidth;
        template.addClass('in');
        $('#loading').remove();
      });
  });
</script>

app/views/images/_template_download.html.erb
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <div class="overlay-wrapper col-xs-4 col-sm-2 template-download">
      <div class="imageuploadify-container">
        <input type="hidden" name="post[image_ids][]" value="{%= file.id %}">
        <button type='button' onclick="RemoveImgPreview(this)" class='btn btn-danger delete btn-delete glyphicon glyphicon-remove'
        data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
        </button>
        <div class="imageuploadify-details preview">
          <img src="{%=file.url%}" class="img-download" alt="" width="100">
        </div>
      </div>
    </div>
  {% } %}
</script>

app/views/images/_template_upload.html.erb
<!-- <script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
      <tr class="template-upload fade">
          <td><span class="preview"></span></td>
          <td width="45%">
              <img src="{%=file.path%}" class="img-responsive"></img>
              <strong class="error text-danger"></strong>

              {% if (!i && !o.options.autoUpload) { %}
                  <button class="btn btn-success start" disabled>
                      <i class="glyphicon glyphicon-upload"></i>
                      Start / resume
                  </button>
              {% } %}
              {% if (!i) { %}
                  <button class="btn btn-danger cancel">
                      <i class="glyphicon glyphicon-ban-circle"></i>
                      Cancel upload
                  </button>
              {% } %}
          </td>
      </tr>
  {% } %}
</script> -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <div class="overlay-wrapper col-xs-4 col-sm-2 template-upload fade">
      <div class="imageuploadify-container">
        <span class="preview"></span>
        <span class="overlay">
          {% if (!i && !o.options.autoUpload) { %}
              <button class="btn btn-success start" disabled>
                  <i class="glyphicon glyphicon-upload"></i>
                  Start / resume
              </button>
          {% } %}
          {% if (!i) { %}
              <div class="sk-circle">
                <div class="sk-circle1 sk-child"></div>
                <div class="sk-circle2 sk-child"></div>
                <div class="sk-circle3 sk-child"></div>
                <div class="sk-circle4 sk-child"></div>
                <div class="sk-circle5 sk-child"></div>
                <div class="sk-circle6 sk-child"></div>
                <div class="sk-circle7 sk-child"></div>
                <div class="sk-circle8 sk-child"></div>
                <div class="sk-circle9 sk-child"></div>
                <div class="sk-circle10 sk-child"></div>
                <div class="sk-circle11 sk-child"></div>
                <div class="sk-circle12 sk-child"></div>
              </div>
          {% } %}
        </span>
      </div>
    </div>
  {% } %}
</script>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing Images</h1>
<%= link_to 'New Image', new_image_path %>
<section class="content-item" id="gallery">
  <div class="container">
    <div class="content-headline">
      <h2>Image gallery</h2>
      <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h3>
    </div>

    <!-- <div class="row"> -->
        <!-- <% @images.each do |image| %>
          <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <a href="#" class="thumbnail">
              <%= image_tag "http://americanconstruction.net/wp-content/uploads/2015/10/upload-empty.png", class: "img-responsive lazy", "data-src": image.image.url%>
            </a>
            <%#= link_to '<i class="fa fa-trash"></i>'.html_safe, image, class: "btn btn-default", method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        <% end %> -->
        <div id="pictures" class="tab-pane">
          <ul class="img-thumbnails">
            <% @images.each do |image| %>
            <li>
              <a href="#" data-rel="colorbox">
                <div class="img">
                  <%= image_tag image.image.url%>
                </div>
                <div class="text">
                  <!-- <div class="inner">Sample Caption on Hover</div> -->
                </div>
              </a>

              <div class="tools tools-bottom">
                <a href="#">
                  <i class="img-icon fa fa-link"></i>
                </a>
                <a href="#">
                  <i class="img-icon fa fa-times red"></i>
                </a>
              </div>
            </li>
            <% end %>
          </ul>
        </div>
  </div>
</section>

app/views/images/new.html.erb
<div class="container">
	<h1>New Image</h1>

	<%= render 'form' %>

	<%= link_to 'Back', images_path %>
</div>

app/views/images/show.html.erb
<dd>Title: <%= @image.title %></dd>
<%= image_tag  @image.image.url, class: "img-responsive" %>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>